exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.14.0"
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      # additional_dependencies: [flake8-docstrings, flake8-debugger, flake8-bugbear, flake8-rst-docstrings]
