[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "trollmoves"
dynamic = ["version"]
description = "Pytroll file utilities"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "Martin Raspaud", email = "martin.raspaud@smhi.se" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "netifaces",
    "posttroll>=1.5.1",
    "pyyaml",
    "pyzmq",
    "trollsift",
    "watchdog!=4.0.0",
]

[project.optional-dependencies]
all = [
    "fsspec",
    "paramiko",
    "pytroll-collectors>=0.16.0",
    "pytroll-watchers>=0.6.0",
    "s3fs",
    "scp",
]
docs = []
fetcher = [
    "pytroll-watchers>=0.6.0",
]
remote_fs = [
    "fsspec",
    "pytroll-collectors>=0.16.0",
]
s3 = [
    "s3fs",
]
server = [
    "paramiko",
    "scp",
]

[project.scripts]
pytroll-fetcher = "trollmoves.fetcher:cli"

[project.urls]
Homepage = "https://github.com/pytroll/trollmoves"

[tool.hatch.build.targets.sdist]
include = [
    "/trollmoves",
]

[tool.hatch.version]
source = "vcs"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[tool.ruff]
line-length = 120
extend-exclude = ["trollmoves/version.py"]  # automatically generated by hatch-vcs

[tool.ruff.lint]
# See https://docs.astral.sh/ruff/rules/
# To add: N, PT, D, B, T20, S, C90
select = ["A", "E", "W", "F", "I", "TID", "Q", "T10"]

[tool.ruff.lint.per-file-ignores]
"trollmoves/tests/*" = ["S101", "S104", "S105"]  # assert allowed in tests
"docs/source/conf.py" = ["D100", "A001"]  # sphinx misbihaving

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10
